/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatSessionKeyRouteImport } from './routes/chat/$sessionKey'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiPersonasRouteImport } from './routes/api/personas'
import { Route as ApiPathsRouteImport } from './routes/api/paths'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiLlmFeaturesRouteImport } from './routes/api/llm-features'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiFollowUpsRouteImport } from './routes/api/follow-ups'
import { Route as ApiAgentsRouteImport } from './routes/api/agents'
import { Route as ApiFilesUploadRouteImport } from './routes/api/files/upload'
import { Route as ApiFilesSaveRouteImport } from './routes/api/files/save'
import { Route as ApiFilesRenameRouteImport } from './routes/api/files/rename'
import { Route as ApiFilesReadRouteImport } from './routes/api/files/read'
import { Route as ApiFilesMkdirRouteImport } from './routes/api/files/mkdir'
import { Route as ApiFilesListRouteImport } from './routes/api/files/list'
import { Route as ApiFilesInfoRouteImport } from './routes/api/files/info'
import { Route as ApiFilesDownloadRouteImport } from './routes/api/files/download'
import { Route as ApiFilesDeleteRouteImport } from './routes/api/files/delete'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatSessionKeyRoute = ChatSessionKeyRouteImport.update({
  id: '/chat/$sessionKey',
  path: '/chat/$sessionKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPersonasRoute = ApiPersonasRouteImport.update({
  id: '/api/personas',
  path: '/api/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPathsRoute = ApiPathsRouteImport.update({
  id: '/api/paths',
  path: '/api/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmFeaturesRoute = ApiLlmFeaturesRouteImport.update({
  id: '/api/llm-features',
  path: '/api/llm-features',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFollowUpsRoute = ApiFollowUpsRouteImport.update({
  id: '/api/follow-ups',
  path: '/api/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRoute = ApiAgentsRouteImport.update({
  id: '/api/agents',
  path: '/api/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesUploadRoute = ApiFilesUploadRouteImport.update({
  id: '/api/files/upload',
  path: '/api/files/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSaveRoute = ApiFilesSaveRouteImport.update({
  id: '/api/files/save',
  path: '/api/files/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRenameRoute = ApiFilesRenameRouteImport.update({
  id: '/api/files/rename',
  path: '/api/files/rename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesReadRoute = ApiFilesReadRouteImport.update({
  id: '/api/files/read',
  path: '/api/files/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesMkdirRoute = ApiFilesMkdirRouteImport.update({
  id: '/api/files/mkdir',
  path: '/api/files/mkdir',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesListRoute = ApiFilesListRouteImport.update({
  id: '/api/files/list',
  path: '/api/files/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesInfoRoute = ApiFilesInfoRouteImport.update({
  id: '/api/files/info',
  path: '/api/files/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesDownloadRoute = ApiFilesDownloadRouteImport.update({
  id: '/api/files/download',
  path: '/api/files/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesDeleteRoute = ApiFilesDeleteRouteImport.update({
  id: '/api/files/delete',
  path: '/api/files/delete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/connect': typeof ConnectRoute
  '/files': typeof FilesRoute
  '/new': typeof NewRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/follow-ups': typeof ApiFollowUpsRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/llm-features': typeof ApiLlmFeaturesRoute
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/personas': typeof ApiPersonasRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/api/files/delete': typeof ApiFilesDeleteRoute
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/info': typeof ApiFilesInfoRoute
  '/api/files/list': typeof ApiFilesListRoute
  '/api/files/mkdir': typeof ApiFilesMkdirRoute
  '/api/files/read': typeof ApiFilesReadRoute
  '/api/files/rename': typeof ApiFilesRenameRoute
  '/api/files/save': typeof ApiFilesSaveRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/connect': typeof ConnectRoute
  '/files': typeof FilesRoute
  '/new': typeof NewRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/follow-ups': typeof ApiFollowUpsRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/llm-features': typeof ApiLlmFeaturesRoute
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/personas': typeof ApiPersonasRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/api/files/delete': typeof ApiFilesDeleteRoute
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/info': typeof ApiFilesInfoRoute
  '/api/files/list': typeof ApiFilesListRoute
  '/api/files/mkdir': typeof ApiFilesMkdirRoute
  '/api/files/read': typeof ApiFilesReadRoute
  '/api/files/rename': typeof ApiFilesRenameRoute
  '/api/files/save': typeof ApiFilesSaveRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/connect': typeof ConnectRoute
  '/files': typeof FilesRoute
  '/new': typeof NewRoute
  '/api/agents': typeof ApiAgentsRoute
  '/api/follow-ups': typeof ApiFollowUpsRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/llm-features': typeof ApiLlmFeaturesRoute
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/personas': typeof ApiPersonasRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/api/files/delete': typeof ApiFilesDeleteRoute
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/info': typeof ApiFilesInfoRoute
  '/api/files/list': typeof ApiFilesListRoute
  '/api/files/mkdir': typeof ApiFilesMkdirRoute
  '/api/files/read': typeof ApiFilesReadRoute
  '/api/files/rename': typeof ApiFilesRenameRoute
  '/api/files/save': typeof ApiFilesSaveRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/connect'
    | '/files'
    | '/new'
    | '/api/agents'
    | '/api/follow-ups'
    | '/api/history'
    | '/api/llm-features'
    | '/api/models'
    | '/api/paths'
    | '/api/personas'
    | '/api/ping'
    | '/api/send'
    | '/api/sessions'
    | '/api/stream'
    | '/api/stt'
    | '/api/tts'
    | '/chat/$sessionKey'
    | '/api/files/delete'
    | '/api/files/download'
    | '/api/files/info'
    | '/api/files/list'
    | '/api/files/mkdir'
    | '/api/files/read'
    | '/api/files/rename'
    | '/api/files/save'
    | '/api/files/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/connect'
    | '/files'
    | '/new'
    | '/api/agents'
    | '/api/follow-ups'
    | '/api/history'
    | '/api/llm-features'
    | '/api/models'
    | '/api/paths'
    | '/api/personas'
    | '/api/ping'
    | '/api/send'
    | '/api/sessions'
    | '/api/stream'
    | '/api/stt'
    | '/api/tts'
    | '/chat/$sessionKey'
    | '/api/files/delete'
    | '/api/files/download'
    | '/api/files/info'
    | '/api/files/list'
    | '/api/files/mkdir'
    | '/api/files/read'
    | '/api/files/rename'
    | '/api/files/save'
    | '/api/files/upload'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/connect'
    | '/files'
    | '/new'
    | '/api/agents'
    | '/api/follow-ups'
    | '/api/history'
    | '/api/llm-features'
    | '/api/models'
    | '/api/paths'
    | '/api/personas'
    | '/api/ping'
    | '/api/send'
    | '/api/sessions'
    | '/api/stream'
    | '/api/stt'
    | '/api/tts'
    | '/chat/$sessionKey'
    | '/api/files/delete'
    | '/api/files/download'
    | '/api/files/info'
    | '/api/files/list'
    | '/api/files/mkdir'
    | '/api/files/read'
    | '/api/files/rename'
    | '/api/files/save'
    | '/api/files/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ConnectRoute: typeof ConnectRoute
  FilesRoute: typeof FilesRoute
  NewRoute: typeof NewRoute
  ApiAgentsRoute: typeof ApiAgentsRoute
  ApiFollowUpsRoute: typeof ApiFollowUpsRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiLlmFeaturesRoute: typeof ApiLlmFeaturesRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiPathsRoute: typeof ApiPathsRoute
  ApiPersonasRoute: typeof ApiPersonasRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiSendRoute: typeof ApiSendRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ChatSessionKeyRoute: typeof ChatSessionKeyRoute
  ApiFilesDeleteRoute: typeof ApiFilesDeleteRoute
  ApiFilesDownloadRoute: typeof ApiFilesDownloadRoute
  ApiFilesInfoRoute: typeof ApiFilesInfoRoute
  ApiFilesListRoute: typeof ApiFilesListRoute
  ApiFilesMkdirRoute: typeof ApiFilesMkdirRoute
  ApiFilesReadRoute: typeof ApiFilesReadRoute
  ApiFilesRenameRoute: typeof ApiFilesRenameRoute
  ApiFilesSaveRoute: typeof ApiFilesSaveRoute
  ApiFilesUploadRoute: typeof ApiFilesUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$sessionKey': {
      id: '/chat/$sessionKey'
      path: '/chat/$sessionKey'
      fullPath: '/chat/$sessionKey'
      preLoaderRoute: typeof ChatSessionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/personas': {
      id: '/api/personas'
      path: '/api/personas'
      fullPath: '/api/personas'
      preLoaderRoute: typeof ApiPersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paths': {
      id: '/api/paths'
      path: '/api/paths'
      fullPath: '/api/paths'
      preLoaderRoute: typeof ApiPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm-features': {
      id: '/api/llm-features'
      path: '/api/llm-features'
      fullPath: '/api/llm-features'
      preLoaderRoute: typeof ApiLlmFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/follow-ups': {
      id: '/api/follow-ups'
      path: '/api/follow-ups'
      fullPath: '/api/follow-ups'
      preLoaderRoute: typeof ApiFollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents': {
      id: '/api/agents'
      path: '/api/agents'
      fullPath: '/api/agents'
      preLoaderRoute: typeof ApiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/upload': {
      id: '/api/files/upload'
      path: '/api/files/upload'
      fullPath: '/api/files/upload'
      preLoaderRoute: typeof ApiFilesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/save': {
      id: '/api/files/save'
      path: '/api/files/save'
      fullPath: '/api/files/save'
      preLoaderRoute: typeof ApiFilesSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/rename': {
      id: '/api/files/rename'
      path: '/api/files/rename'
      fullPath: '/api/files/rename'
      preLoaderRoute: typeof ApiFilesRenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/read': {
      id: '/api/files/read'
      path: '/api/files/read'
      fullPath: '/api/files/read'
      preLoaderRoute: typeof ApiFilesReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/mkdir': {
      id: '/api/files/mkdir'
      path: '/api/files/mkdir'
      fullPath: '/api/files/mkdir'
      preLoaderRoute: typeof ApiFilesMkdirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/list': {
      id: '/api/files/list'
      path: '/api/files/list'
      fullPath: '/api/files/list'
      preLoaderRoute: typeof ApiFilesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/info': {
      id: '/api/files/info'
      path: '/api/files/info'
      fullPath: '/api/files/info'
      preLoaderRoute: typeof ApiFilesInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/download': {
      id: '/api/files/download'
      path: '/api/files/download'
      fullPath: '/api/files/download'
      preLoaderRoute: typeof ApiFilesDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/delete': {
      id: '/api/files/delete'
      path: '/api/files/delete'
      fullPath: '/api/files/delete'
      preLoaderRoute: typeof ApiFilesDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ConnectRoute: ConnectRoute,
  FilesRoute: FilesRoute,
  NewRoute: NewRoute,
  ApiAgentsRoute: ApiAgentsRoute,
  ApiFollowUpsRoute: ApiFollowUpsRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiLlmFeaturesRoute: ApiLlmFeaturesRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiPathsRoute: ApiPathsRoute,
  ApiPersonasRoute: ApiPersonasRoute,
  ApiPingRoute: ApiPingRoute,
  ApiSendRoute: ApiSendRoute,
  ApiSessionsRoute: ApiSessionsRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  ChatSessionKeyRoute: ChatSessionKeyRoute,
  ApiFilesDeleteRoute: ApiFilesDeleteRoute,
  ApiFilesDownloadRoute: ApiFilesDownloadRoute,
  ApiFilesInfoRoute: ApiFilesInfoRoute,
  ApiFilesListRoute: ApiFilesListRoute,
  ApiFilesMkdirRoute: ApiFilesMkdirRoute,
  ApiFilesReadRoute: ApiFilesReadRoute,
  ApiFilesRenameRoute: ApiFilesRenameRoute,
  ApiFilesSaveRoute: ApiFilesSaveRoute,
  ApiFilesUploadRoute: ApiFilesUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
